version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - "> 9.4.35.v20201120"
  - dependency-name: io.quarkus:quarkus-maven-plugin
    versions:
    - 1.11.1.Final
    - 1.11.2.Final
    - 1.11.3.Final
    - 1.12.1.Final
    - 1.12.2.Final
    - 1.13.1.Final
    - 1.13.2.Final
  - dependency-name: io.quarkus:quarkus-universe-bom
    versions:
    - 1.11.1.Final
    - 1.11.2.Final
    - 1.12.0.Final
    - 1.12.1.Final
    - 1.13.0.Final
    - 1.13.1.Final
    - 1.13.2.Final
  - dependency-name: org.kohsuke:github-api
    versions:
    - "1.123"
    - "1.124"
    - "1.125"
    - "1.127"
